
CREATE DATABASE QL_GVHS
go
USE QL_GVHS
go
CREATE TABLE LOP(
MALOP VARCHAR(10) PRIMARY KEY,
TENLOP VARCHAR(15)
)
go
CREATE TABLE GIAO_VIEN(
MAGV varCHAR(10) PRIMARY KEY,
TENGV NVARCHAR(40),
THONGTIN NVARCHAR(100),
CNLOP VARCHAR(10),
GDAY  VARCHAR(10) REFERENCES LOP(MALOP)
)
go
CREATE TABLE HOSOHOCSINH(
MAHS varCHAR(10) PRIMARY KEY,
TENHS NVARCHAR(40),
GIOITINH nvarCHAR(5) CHECK (GIOITINH IN (N'Nam',N'Nữ')),
NGAYSINH DATE,
DIACHI NVARCHAR(100),
SODIENTHOAI VARCHAR(20),
HOTENBO NVARCHAR(40),
HOTENME NVARCHAR(40),
LOPHOC VARCHAR(10) REFERENCES LOP(MALOP)
)
go

CREATE TABLE MONHOC(
MAMON VARCHAR(10) PRIMARY KEY,
TENMON NVARCHAR(50),
GHICHU NVARCHAR(100)
)
go
CREATE TABLE BANGDIEM(
MAHS varCHAR(10) REFERENCES HOSOHOCSINH(MAHS),
MAMON VARCHAR(10) REFERENCES MONHOC(MAMON),
HOCKY varCHAR(10),
DIEMMIENG FLOAT,
DIEM15P FLOAT,
DIEM1TIET FLOAT,
DIEMHOCKY FLOAT,
PRIMARY KEY(MAHS,MAMON)
)
go
CREATE TABLE Login(
Username VARCHAR(50) PRIMARY KEY,
Pass VARCHAR(50),
)
go
 

 go
CREATE PROC ThemGV(@MAGV varchar(10),@TENGV  nvarchar(40),@THONGTIN nvarchar(100),@CNLOP  varchar(10),@GDAY  VARCHAR(10)) AS
BEGIN
	INSERT INTO dbo.GIAO_VIEN
        ( MAGV, TENGV, THONGTIN, CNLOP, GDAY)
VALUES  ( @MAGV,@TENGV,@THONGTIN,@CNLOP,@GDAY)
END

go
CREATE PROC SuaGV (@MAGV varchar(10),@TENGV  nvarchar(40),@THONGTIN nvarchar(100),@CNLOP  varchar(10),@GDAY  VARCHAR(10)) AS
BEGIN
	UPDATE dbo.GIAO_VIEN SET 
	TENGV = @TENGV,THONGTIN = @THONGTIN,CNLOP = @CNLOP,GDAY =@GDAY WHERE MAGV = @MAGV
END
go
 CREATE PROC XoaGV(@MAGV varchar(10)) AS
 BEGIN
		DELETE FROM dbo.GIAO_VIEN WHERE MAGV = @MAGV
 END
 go
 CREATE PROC dbo.KiemTraDN(@Username VARCHAR(50),@Pass varchar(50)) AS 
 BEGIN
	SELECT * FROM dbo.Login WHERE Username = @Username AND Pass = @Pass
 END
 go
CREATE PROC ThemTK(@Username VARCHAR(50),@Pass varchar(50)) AS 
 BEGIN
	INSERT INTO dbo.Login
	        ( Username, Pass )
	VALUES  ( @Username,@Pass )
 END
 go
 THEMTK 'a','a'
 go
 CREATE PROC XOAHS (@MAHS varchar(10))
	AS
	BEGIN 
				DELETE FROM dbo.HOSOHOCSINH
				WHERE MAHS=@MAHS
	END
	--exec XOAHS 'HS01'
go
create proc TimKiemHSTheoMAHS (@MAHS varchar(10)) as
begin
	select * from HOSOHOCSINH
	where MAHS=@MAHS
end
go
--execute TimKiemHSTheoMAHS 'HS002'
create proc TimKiemHSTheoTen (@TENHS nvarchar(40)) as
begin
	select * from HOSOHOCSINH
	where TENHS like '%'+N'@TENHS'+'%'
end
go
create proc TimKiemGiangDay (@GDAY varchar(10)) as
begin
	select * from GIAO_VIEN
	where GDAY=@GDAY
END

 INSERT INTO dbo.MONHOC
         ( MAMON, TENMON, GHICHU )
 VALUES  ( '', N'',N'')
-- thêm sửa xóa môn học và lớp học
go
CREATE PROC ThemMH(@MAMON varchar(10),@TENMON nvarchar(40),@GHICHU nvarchar(100)) AS
BEGIN
	 INSERT INTO dbo.MONHOC
         ( MAMON, TENMON, GHICHU )
	VALUES  ( @MAMON,@TENMON,@GHICHU)
END
go

CREATE PROC SuaMH (@MAMON varchar(10),@TENMON nvarchar(40),@GHICHU nvarchar(100)) AS
BEGIN
	UPDATE dbo.MONHOC SET 
	TENMON = @TENMON,GHICHU = @GHICHU WHERE MAMON = @MAMON
END
go
CREATE PROC THEMHS (@MAHS varchar(10),@TENHS NVARCHAR(40),@GIOITINH nvarCHAR(5),@NGAYSINH DATE,@DIACHI NVARCHAR(100),@LOPHOC VARCHAR(10),@SODIENTHOAI VARCHAR(20))
	AS
	BEGIN 
		INSERT INTO  dbo.HOSOHOCSINH (MAHS,TENHS,GIOITINH,NGAYSINH,DIACHI,LOPHOC,SODIENTHOAI)
		VALUES  ( @MAHS,@TENHS,@GIOITINH,@NGAYSINH,@DIACHI,@LOPHOC,@SODIENTHOAI )
	END
go
CREATE PROC SUAHS (@MAHS varchar(10),@TENHS NVARCHAR(40),@GIOITINH nvarCHAR(5),@NGAYSINH DATE,@DIACHI NVARCHAR(100),@LOPHOC VARCHAR(10),@SODIENTHOAI VARCHAR(20))
	AS
	BEGIN 
		UPDATE dbo.HOSOHOCSINH
		SET TENHS = @TENHS,GIOITINH = @GIOITINH,NGAYSINH = @NGAYSINH, DIACHI = @DIACHI, LOPHOC = @LOPHOC, SODIENTHOAI = @SODIENTHOAI Where MAHS = @MAHS
	END
go

 CREATE PROC XoaMH(@MAMON varchar(10)) AS
 BEGIN
		DELETE FROM dbo.MONHOC WHERE MAMON = @MAMON
 END
 GO
-- Lớp Học 
 
CREATE PROC ThemLH(@MALOP VARCHAR(10),@TENLOP VARCHAR(15)) AS
BEGIN
	 INSERT INTO dbo.LOP
	         ( MALOP, TENLOP )
	 VALUES  (@MALOP,@TENLOP ) 
END
go

CREATE PROC SuaLH (@MALOP VARCHAR(10),@TENLOP VARCHAR(15)) AS
BEGIN
	UPDATE dbo.LOP SET 
	TENLOP = @TENLOP WHERE MALOP = @MALOP
END
go
  
CREATE PROC ThemBD(@MAHS varCHAR(10),@MAMON varCHAR(15),@HOCKY varCHAR(10),@DIEMMIENG FLOAT,@DIEM15P FLOAT,@DIEM1TIET FLOAT,@DIEMHOCKY FLOAT) AS
BEGIN
	 INSERT INTO dbo.BANGDIEM
	 VALUES  (@MAHS,@MAMON,@HOCKY,@DIEMMIENG,@DIEM15P,@DIEM1TIET,@DIEMHOCKY) 
END
go


CREATE PROC SuaBD (@MAHS varCHAR(10),@MAMON varCHAR(15),@HOCKY varCHAR(10),@DIEMMIENG FLOAT,@DIEM15P FLOAT,@DIEM1TIET FLOAT,@DIEMHOCKY FLOAT) AS
BEGIN
	UPDATE dbo.BANGDIEM SET 
	HOCKY=@HOCKY, DIEM15P=@DIEM15P, DIEMMIENG=@DIEMMIENG,DIEM1TIET=@DIEM1TIET,DIEMHOCKY=@DIEMHOCKY 
	WHERE MAHS=@MAHS AND MAMON=@MAMON
END
GO
CREATE PROC XoaBD(@MAHS varCHAR(10),@MAMON varCHAR(15)) AS
 BEGIN
		DELETE FROM dbo.BANGDIEM WHERE MAMON = @MAMON AND MAHS=@MAHS
 END
 