CREATE DATABASE QL_GVHS
USE QL_GVHS

CREATE TABLE LOP(
MALOP VARCHAR(10) PRIMARY KEY,
TENLOP VARCHAR(15)
)

CREATE TABLE GIAO_VIEN(
MAGV CHAR(10) PRIMARY KEY,
TENGV NVARCHAR(40),
THONGTIN NVARCHAR(100),
CNLOP VARCHAR(10),
GDAY  VARCHAR(10) REFERENCES LOP(MALOP)
)

CREATE TABLE HOSOHOCSINH(
MAHS CHAR(10) PRIMARY KEY,
TENHS NVARCHAR(40),
GIOITINH CHAR(3) CHECK (GIOITINH IN ('NAM','NU')),
NGAYSINH DATE,
DIACHI NVARCHAR(100),
SODIENTHOAI INT,
HOTENBO NVARCHAR(40),
HOTENME NVARCHAR(40),
LOPHOC VARCHAR(10) REFERENCES LOP(MALOP)
)

CREATE TABLE MONHOC(
MAMON CHAR(10) PRIMARY KEY,
TENMON NVARCHAR(50),
GHICHU NVARCHAR(100)
)

CREATE TABLE BANGDIEM(
MAHS CHAR(10) REFERENCES HOSOHOCSINH(MAHS),
MAMON CHAR(10) REFERENCES MONHOC(MAMON),
HOCKY CHAR(10),
DIEMMIENG FLOAT,
DIEM15P FLOAT,
DIEM1TIET FLOAT,
DIEMHOCKY FLOAT,
PRIMARY KEY(MAHS,MAMON)
)

CREATE TABLE Login(
Username VARCHAR(50) PRIMARY KEY,
Pass VARCHAR(50),
)

INSERT INTO dbo.LOP
        ( MALOP, TENLOP )
VALUES  ( '01', -- MALOP - varchar(10)
          'A1'  -- TENLOP - varchar(15)
          )
		  INSERT INTO dbo.LOP
        ( MALOP, TENLOP )
VALUES  ( '02', -- MALOP - varchar(10)
          'A2'  -- TENLOP - varchar(15)
          )
		  INSERT INTO dbo.LOP
        ( MALOP, TENLOP )
VALUES  ( '03', -- MALOP - varchar(10)
          'A3'  -- TENLOP - varchar(15)
          )
		  INSERT INTO dbo.LOP
        ( MALOP, TENLOP )
VALUES  ( '04', -- MALOP - varchar(10)
          'A4'  -- TENLOP - varchar(15)
          )
		  INSERT INTO dbo.LOP
        ( MALOP, TENLOP )
VALUES  ( '05', -- MALOP - varchar(10)
          'A5'  -- TENLOP - varchar(15)
          )
		  INSERT INTO dbo.LOP
        ( MALOP, TENLOP )
VALUES  ( '07', -- MALOP - varchar(10)
          'A7'  -- TENLOP - varchar(15)
          )
 
CREATE PROC ThemGV(@MAGV char(10),@TENGV  nvarchar(40),@THONGTIN nvarchar(100),@CNLOP  varchar(10),@GDAY  VARCHAR(10)) AS
BEGIN
	INSERT INTO dbo.GIAO_VIEN
        ( MAGV, TENGV, THONGTIN, CNLOP, GDAY)
VALUES  ( @MAGV,@TENGV,@THONGTIN,@CNLOP,@GDAY)
END

ThemGV 'GV01',N'Chu Văn Thịnh',N'Ba Vì','','07'

CREATE PROC SuaGV (@MAGV char(10),@TENGV  nvarchar(40),@THONGTIN nvarchar(100),@CNLOP  varchar(10),@GDAY  VARCHAR(10)) AS
BEGIN
	UPDATE dbo.GIAO_VIEN SET 
	TENGV = @TENGV,THONGTIN = @THONGTIN,CNLOP = @CNLOP,GDAY =@GDAY WHERE MAGV = @MAGV
END

 CREATE PROC XoaGV(@MAGV char(10)) AS
 BEGIN
		DELETE FROM dbo.GIAO_VIEN WHERE MAGV = @MAGV
 end